#ifndef KERNEL_EXCEPTIONS_H_INCLUDED
#define KERNEL_EXCEPTIONS_H_INCLUDED

#ifdef __GNUC__
    #define _EXCEPT_QUALIFIER _GLIBCXX_NOEXCEPT
#else
    #define _EXCEPT_QUALIFIER
#endif

#endif // KERNEL_EXCEPTIONS_H_INCLUDED
