# A set of helper functions for reading data from files

# Read variables from file (KEY=VALUE)
# FILE_NAME - file name, must be in a root directory
function (read_variables_from_file FILE_NAME)
    file(STRINGS ./${FILE_NAME} PROJECT_VARS)
    message(STATUS "Setting up project variables from the file: '${PROJECT_VARIABLES_FILENAME}'")
        foreach(LINE ${PROJECT_VARS})
            string(REGEX MATCH "(.*)=(.*)" _ ${LINE})
            set(${CMAKE_MATCH_1} ${CMAKE_MATCH_2} PARENT_SCOPE)
            message(STATUS "\t ${CMAKE_MATCH_1} = ${CMAKE_MATCH_2}")
        endforeach()
endfunction()

function (read_list_variables_from_file FILE_NAME)
    file(STRINGS ./${FILE_NAME} PROJECT_VARS)
    message(STATUS "Setting up project list variables from the file: '${PROJECT_VARIABLES_FILENAME}'")
        foreach(LINE ${PROJECT_VARS})
            string(REGEX MATCH "(.*):=(.*)" _ ${LINE})
            string(REPLACE " " ";" STR_TO_LIST ${CMAKE_MATCH_2})
            separate_arguments(CMAKE_MATCH_2)
            set(${CMAKE_MATCH_1} ${CMAKE_MATCH_2} PARENT_SCOPE)
            message(STATUS "\t ${CMAKE_MATCH_1} = ${STR_TO_LIST}")
        endforeach()
endfunction()