#ifndef ART_H_INCLUDED
#define ART_H_INCLUDED

class wxBitmap;

// The functions provide default icons for buttons.
// Icons are stored as a binary data in 'icons.h' header (generated by 'bin2c' utility).
// See original raw data in 'assets'-folder
namespace modeller {
    namespace art {
        enum Icon
        {
            ICO_EMPTY,
            ICO_VIEW_TOP,
            ICO_VIEW_LEFT,
            ICO_VIEW_BOTTOM,
            ICO_VIEW_RIGHT,
            ICO_VIEW_FRONT,
            ICO_VIEW_BACK,
            ICO_VIEW_ISO,
            ICO_SKETCH_MODE,
            ICO_SKETCH_POINT,
            ICO_SKETCH_LINE,
        };

        wxBitmap get_icon(Icon icon);
    }
}

#endif // ART_H_INCLUDED
